-- Schema inicial para o Raio-X da Experiência do Cliente.
-- Execute no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.respondents (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  whatsapp text,
  whatsapp_opt_in boolean not null default false,
  role text,
  company_stage text,
  company_size text,
  customer_relationship_stage text,
  main_challenge text,
  created_at timestamptz not null default now()
);

create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  respondent_id uuid not null references public.respondents(id) on delete cascade,
  question_id text not null,
  block text not null,
  score integer not null check (score between 1 and 5),
  answer_label text,
  observation text
);

create table if not exists public.results (
  id bigint generated by default as identity primary key,
  respondent_id uuid not null references public.respondents(id) on delete cascade,
  overall_score numeric not null,
  clarity_score numeric not null,
  conducting_threads_score numeric not null,
  success_keys_score numeric not null,
  repurchase_score numeric not null,
  next_step_score numeric not null,
  primary_profile text not null,
  professional_moment text not null,
  created_at timestamptz not null default now()
);

create index if not exists answers_respondent_id_idx on public.answers(respondent_id);
create index if not exists results_respondent_id_idx on public.results(respondent_id);
create index if not exists respondents_created_at_idx on public.respondents(created_at);

-- RLS: o frontend usa a anon key para inserir diagnósticos.
-- Não é permitido ler ou atualizar registros pelo cliente público.
alter table public.respondents enable row level security;
alter table public.answers enable row level security;
alter table public.results enable row level security;

drop policy if exists "public can insert respondents" on public.respondents;
create policy "public can insert respondents"
on public.respondents for insert
to anon with check (true);

drop policy if exists "public can insert answers" on public.answers;
create policy "public can insert answers"
on public.answers for insert
to anon with check (true);

drop policy if exists "public can insert results" on public.results;
create policy "public can insert results"
on public.results for insert
to anon with check (true);

-- Não crie policies de SELECT para anon.
-- Dados pessoais devem ser consultados apenas por um backend/admin autenticado.
