import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { DiagnosticResult, ContextAnswers, Lead, AnswerRecord } from "@/lib/types";
import { PROFILES } from "@/lib/profiles";
import { MOMENTS } from "@/lib/moments";
import { getContextLabel } from "@/lib/context-questions";
import { QUESTIONS } from "@/lib/questions";
const C={navy:"#071827",mid:"#0D2438",electric:"#18B8E8",gold:"#F5C85B",cream:"#F7F4EA",muted:"#8FA3B5",line:"#1E3448"};
const s=StyleSheet.create({page:{backgroundColor:C.navy,color:C.cream,padding:40,fontSize:10,fontFamily:"Helvetica"},cover:{backgroundColor:C.navy,padding:56,justifyContent:"space-between"},kicker:{fontSize:8,letterSpacing:3,color:C.electric,marginBottom:10},title:{fontSize:28,fontFamily:"Helvetica-Bold",color:C.cream,lineHeight:1.2},goldTitle:{fontSize:28,fontFamily:"Helvetica-Bold",color:C.gold,lineHeight:1.2,marginBottom:20},body:{fontSize:10,color:C.muted,lineHeight:1.55},section:{marginBottom:20},h2:{fontSize:16,fontFamily:"Helvetica-Bold",color:C.cream,marginBottom:10},score:{fontSize:40,fontFamily:"Helvetica-Bold",color:C.cream},row:{flexDirection:"row",justifyContent:"space-between",marginBottom:8},label:{fontSize:9,color:C.cream},value:{fontSize:9,color:C.gold,fontFamily:"Helvetica-Bold"},track:{height:6,backgroundColor:C.line,borderRadius:3},fill:{height:6,backgroundColor:C.electric,borderRadius:3},callout:{borderLeftWidth:3,borderLeftColor:C.gold,backgroundColor:"#102536",padding:12,marginBottom:16},calloutTitle:{fontSize:11,fontFamily:"Helvetica-Bold",color:C.gold,marginBottom:5},calloutBody:{fontSize:9,color:C.cream,lineHeight:1.5},answer:{borderBottomWidth:1,borderBottomColor:C.line,paddingBottom:8,marginBottom:8},small:{fontSize:8,color:C.muted},footer:{fontSize:8,color:C.muted,textAlign:"center",marginTop:20}});
const labels:{key:keyof DiagnosticResult["dimensions"];label:string}[]=[{key:"clareza",label:"Clareza"},{key:"fiosCondutores",label:"Fios Condutores"},{key:"chavesDoSucesso",label:"Chaves do Sucesso"},{key:"recompra",label:"Mola da Recompra"},{key:"proximoPasso",label:"Próximo Passo"}];
export function DiagnosticPDF({result,context,lead,answers}:{result:DiagnosticResult;context:ContextAnswers;lead?:Lead;answers:AnswerRecord[]}){const p=PROFILES[result.primaryProfile],m=MOMENTS[result.professionalMoment];return <Document title="Raio-X da Experiência do Cliente"><Page size="A4" style={s.cover}><View><Text style={s.kicker}>MAGIA DOS DETALHES · DIAGNÓSTICO</Text><Text style={s.title}>Raio-X da</Text><Text style={s.goldTitle}>Experiência do Cliente</Text><Text style={s.body}>Um retrato do momento atual da sua experiência — e do detalhe que merece atenção primeiro.</Text></View><View><Text style={s.small}>{lead?.name?`Preparado para ${lead.name}`:"Diagnóstico personalizado"}</Text><Text style={s.footer}>Phillipe Lontra · Idealizador da Magia dos Detalhes</Text></View></Page><Page size="A4" style={s.page}><View style={s.section}><Text style={s.kicker}>SEU DIAGNÓSTICO</Text><Text style={s.h2}>{p.title}</Text><Text style={s.body}>{p.interpretation}</Text></View><View style={s.callout}><Text style={s.calloutTitle}>Seu momento profissional</Text><Text style={s.calloutBody}>{m.label} — {m.description}</Text></View><View style={s.section}><Text style={s.h2}>Sua jornada em cinco dimensões</Text><Text style={s.score}> {result.overall}<Text style={s.small}> / 100 maturidade geral</Text></Text>{labels.map(x=><View key={x.key} style={{marginTop:12}}><View style={s.row}><Text style={s.label}>{x.label}</Text><Text style={s.value}>{result.dimensions[x.key]}%</Text></View><View style={s.track}><View style={[s.fill,{width:`${result.dimensions[x.key]}%`}]}/></View></View>)}</View><View style={s.callout}><Text style={s.calloutTitle}>Foco para os próximos 90 dias</Text><Text style={s.calloutBody}>Agora você sabe onde começar. Não é necessário melhorar toda a experiência de uma vez; escolha o ponto que mais merece atenção e transforme-o em ação observável.</Text></View></Page><Page size="A4" style={s.page}><View style={s.section}><Text style={s.kicker}>SUAS RESPOSTAS</Text><Text style={s.h2}>O que suas respostas mostraram</Text>{result.signals.map((x,i)=><Text key={i} style={{...s.body,marginBottom:7}}>{x.type==="positive"?"✓":"⚠"} {x.text}</Text>)}</View><View style={s.section}><Text style={s.h2}>Perguntas e respostas</Text>{answers.map(a=>{const q=QUESTIONS.find(q=>q.id===a.questionId);const opt=q?.options.find(o=>o.value===a.score);return <View key={a.questionId} style={s.answer}><Text style={s.label}>{q?.text}</Text><Text style={s.small}>{opt?.label} · {a.score}/5</Text>{a.observation&&<Text style={s.small}>Observação: {a.observation}</Text>}</View>})}</View>{context.role&&<Text style={s.small}>Perfil: {getContextLabel("role",context.role)}</Text>}</Page></Document>}
